export PATH=$PATH:$HOME/.local/bin
export ZSH=$HOME/.oh-my-zsh
export GPG_TTY=$(tty)
export LANG=en_US.UTF-8
export DISPLAY=0.0:0

zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_ed25519  
zstyle :omz:plugins:ssh-agent lifetime
plugins=(git ssh-agent)
ZSH_THEME="powerlevel10k/powerlevel10k"

source ~/.zplug/init.zsh
source ~/.powerlevel10k/powerlevel10k.zsh-theme

zplug "agkozak/zsh-z"
zplug load

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="false"
DISABLE_AUTO_UPDATE="false"
CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
LS_COLORS='ow=01;36;40'
export LS_COLORS 

source $HOME/.cargo/env
source $HOME/.zshrc_local
. ~/.oh-my-zsh/oh-my-zsh.sh
